# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT

name: "CI"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: 🦀 Setup Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: clippy, rustfmt

      - name: 🛠️ Setup sccache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
        with:
          # renovate: datasource=github-releases depName=mozilla/sccache versioning=semver
          version: "v0.18.0"

      - name: 🔗 Enable sccache for cargo
        shell: bash
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=${SCCACHE_PATH}" >> "$GITHUB_ENV"

      - name: 🎨 Check formatting
        run: cargo fmt -- --check

      - name: 📎 Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: 🧪 Test
        run: cargo test

  typos:
    name: 📝 Check typos
    if: always()
    uses: hrzlgnm/actions/.github/workflows/typos-reusable.yml@03b79955b43e4b4ae1678541e9d315d4f24c847d # v2.14.8

  all-required-green: # This job does nothing and is only used for the branch protection
    name: CI Status
    runs-on: ubuntu-latest
    needs:
      - ci
      - typos
    if: always()
    steps:
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@a638d6464689bbb24c325bb3fe9404d63a913030
        with:
          jobs: ${{ toJSON(needs) }}
